Bound properties to values
LeaVerou/css3test pull request #237
Opened 2023-03-19 21:58 UTC by SebastianZ

Moved the properties to test the values for to the individual values. This allows to provide different properties for the values.

Fixes #184

Sebastian

2023-03-20 17:50 UTC, LeaVerou requested changes
This seems extremely repetitive. Why not specify them in the root and override them in individual features if/when needed?

2023-03-20 19:38 UTC, SebastianZ commented
> This seems extremely repetitive. Why not specify them in the root and override them in individual features if/when needed?

I've answered that in #184.

Sebastian

2023-03-21 22:16 UTC, SebastianZ commented
@LeaVerou Changed. Please have another look!

Sebastian

2023-03-22 18:25 UTC, LeaVerou commented
Hi there,

I tried to review the diff, but it's very difficult due to the number of unrelated changes included in it. Anyhow, as long as you can still specify properties globally and don't have to repeat them on every single test, I trust you that the changes are fine.

2023-03-22 18:26 UTC, LeaVerou approved these changes

2023-03-22 18:26 UTC, LeaVerou commented on tests/css-values-4.js
> +		'math functions in calc()': {
This is also unrelated to this PR

2023-03-22 18:26 UTC, LeaVerou commented
(approved so that any pending comments would be flushed, but I stopped leaving comments after a while because they'd be all "this is unrelated, and this, and this, and this"

2023-03-23 20:33 UTC, SebastianZ commented
> I tried to review the diff, but it's very difficult due to the number of unrelated changes included in it.

Ok, let's close this in favor of #238 which only includes changes related to this new feature.

I'll make the unrelated changes separately.

Seastian

2023-03-23 20:33 UTC, closed without merging